git:
  depth: false
sudo: required
language: node_js
node_js:
  - '10'
cache: 
  yarn: true
  directories:
  - node_modules
before_install:
  - curl -o- -L https://yarnpkg.com/install.sh | bash -s -- --version 1.17.3
  - export PATH="$HOME/.yarn/bin:$PATH"
install: yarn install --no-progress --frozen-lockfile
stages:
  - lint
  - name: next-version
    if: branch = master AND type = push AND commit_message !~ /(release)/
jobs:
  include:
    - stage: lint
      script: yarn lint && yarn test
    - stage: next-version
      script: skip
      if: branch = master AND type = push AND commit_message !~ /(release)/
        before_deploy:
          - git config --local user.name "TravisCI"
          - git config --local user.email "frontend@xcritical.software"        
          - git remote set-url origin https://${GH_TOKEN}@github.com/xcritical-software/xc-front-kit.git > /dev/null 2>&1
          - echo "//registry.npmjs.org/:_authToken=\${NPM_TOKEN}" >> $HOME/.npmrc 2> /dev/null
          - git fetch --tags --force
          - git checkout master
          - git pull
          - yarn boltify version --loglevel silly --message "chore(release):" --no-push
        after_deploy: 
          - git push --follow-tags --no-verify
        deploy:
          provider: script
          script: yarn build:lastcommit && npm run deploy
          skip_cleanup: true
          on:
            branch: master
      